require 'rspec'
require 'date'
require 'pry'

require_relative '../models/cage'
require_relative '../models/employee'
require_relative '../models/reptile'
require_relative '../models/fox'
require_relative '../models/gorilla'
require_relative '../models/python'
require_relative '../models/zoo'
